server:
  port: 8083

spring:
  application:
    name: cloud-zjx-provider-hi
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka