server:
  port: 12011

spring:
  application:
    name: cloud-zjx-txlcn-serviceA
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.160.128:3306/txlcn?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zjx123
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

tx-lcn:
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
  client:
    manager-address: 192.168.0.8:8070

feign:
  hystrix:
    enabled: true