server:
  port: 12012

spring:
  application:
    name: cloud-zjx-txlcn-serviceC
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.160.128:3306/txlcn?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zjx123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

#ribbon:
#  MaxAutoRetriesNextServer: 0
#  ReadTimeout: 5000
#  ConnectTimeout: 5000

## tx-manager 配置
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  ribbon:
    loadbalancer:
      dtx.enabled: true