server:
  port: 7970

spring:
  application:
    name: cloud-zjx-txlcn-tm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.160.128:3306/txlcn?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zjx123
  redis:
    host: 192.168.160.128
    port: 6379
    password: zjx123  # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    database: 0 # Redis数据库索引(默认为0)
    jedis:
      pool:
        max-active: 9  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 9 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true