server:
  port: 8081

spring:
  application:
    name: cloud-zjx-gateway-ratelimit
  cloud:
    gateway:
      routes:
        - id: limit_route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'   #用于限流的键的解析器的Bean对象的名字，从 Spring 容器中获取 Bean 对象
                redis-rate-limiter.replenishRate: 1   #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 3   #令牌桶总容量
  redis:
    host: 192.168.160.128
    port: 6379
    database: 0
    password: zjx123