server:
  port: 8762

spring:
  application:
    name: cloud-zjx-provider
  #zipkin server
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true