server:
  port: 9094

spring:
  application:
    name: cloud-zjx-seata-commodity

  cloud:
    alibaba:
      seata:
        tx-service-group: zjx_tx_group  # 与seata server的配置一致 vgroupMapping.zjx_tx_group = "default"， seata server要注册到注册中心

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.160.128:3306/db_commodity?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zjx123
    redis:
      # 单机
      #host: 192.168.160.128
      #port: 6379
      # 集群
      cluster:
        nodes:
          - 192.168.160.128:6379
          - 192.168.160.128:6380
          - 192.168.160.128:6381
      # 哨兵
      sentinel:
        master: mymaster
        nodes:
          - 192.168.160.128:26379
          - 192.168.160.128:26380
          - 192.168.160.128:26381
      password: zjx123  # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      database: 0 # Redis数据库索引(默认为0)
      jedis:
        pool:
          max-active: 9  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 9 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zjx.entity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
          strategy: SEMAPHORE #这里将线程策略设置为SEMAPHORE,防止与oauth2与feginclient子线程获取不到用户认证信息

logging:
  level:
    io:
      seata: info
    com.zjx.mapper: debug