server:
  port: 8768

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cloud-zjx-config-server
  #Git config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jackyzheng123/springCloudConfig/
          searchPaths: resp
          username:
          password:
      label: master