server:
  port: 8767

spring:
  application:
    name: cloud-zjx-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cloud-zjx-ribbon
    api-b:
      path: /api-b/**
      serviceId: cloud-zjx-feign