server:
  port: 8081

spring:
  application:
    name: cloud-zjx-provider-zipkin
  #zipkin server
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka